services:
  oracle:
    image: gvenzl/oracle-free:23.4-slim-faststart
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=petclinic
      - APP_USER=petclinic
      - APP_USER_PASSWORD=petclinic
