---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: servicebinding.io/oracle
stringData:
  type: "oracle"
  provider: "oracle"
  host: "demo-db"
  port: "1521"
  database: "FREEPDB1"
  username: "petclinic"
  password: "petclinic"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-db
spec:
  ports:
    - port: 1521
  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - image: gvenzl/oracle-free:23.4-slim-faststart
          name: oracle
          env:
            - name: ORACLE_PASSWORD
              value: petclinic
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: APP_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
          ports:
            - containerPort: 1521
              name: oracle
          livenessProbe:
            tcpSocket:
              port: oracle
          readinessProbe:
            tcpSocket:
              port: oracle
          startupProbe:
            tcpSocket:
              port: oracle
